# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 06:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField(null=True)),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races_app.Horse')),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races_app.BetType')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races_app.Race')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='races_app.User')),
                ('nickname', models.CharField(max_length=127)),
            ],
            bases=('races_app.user',),
        ),
        migrations.CreateModel(
            name='Bookmaker',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='races_app.User')),
            ],
            bases=('races_app.user',),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='races_app.User')),
                ('phone', models.CharField(max_length=15)),
            ],
            bases=('races_app.user',),
        ),
        migrations.AddField(
            model_name='participation',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races_app.Race'),
        ),
        migrations.AddField(
            model_name='horse',
            name='races',
            field=models.ManyToManyField(through='races_app.Participation', to='races_app.Race'),
        ),
        migrations.AddField(
            model_name='bet',
            name='bet_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races_app.BetType'),
        ),
        migrations.AddField(
            model_name='bet',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races_app.Race'),
        ),
        migrations.AddField(
            model_name='rate',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races_app.Bookmaker'),
        ),
        migrations.AddField(
            model_name='bet',
            name='approver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='races_app.Administrator'),
        ),
        migrations.AddField(
            model_name='bet',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races_app.Client'),
        ),
    ]
