# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 22:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('races_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='horses',
        ),
        migrations.AlterField(
            model_name='participation',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='races_app.Race'),
        ),
    ]
