# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races_app', '0002_auto_20170918_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='approved',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bet',
            name='bet',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bet',
            name='win',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bettype',
            name='type',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='race',
            name='date',
            field=models.DateTimeField(default='1970-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='race',
            name='loops',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rate',
            name='rating',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
