# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races_app', '0002_auto_20171104_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='approved',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='bet',
            name='win',
            field=models.NullBooleanField(),
        ),
    ]
