# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races_app', '0003_auto_20170918_0759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horse',
            name='races',
        ),
        migrations.AddField(
            model_name='race',
            name='horses',
            field=models.ManyToManyField(through='races_app.Participation', to='races_app.Horse'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='place',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
