# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 10:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('races_app', '0003_auto_20171105_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='bet_type',
        ),
    ]
