# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 11:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('races_app', '0004_remove_bet_bet_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='approver',
        ),
    ]
