# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races_app', '0005_remove_bet_approver'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='token',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
