# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 18:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('races_app', '0006_userdetail_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='token',
        ),
    ]
