#!/usr/bin/env bash
version: '2.1'
services:

  database:
      image: postgres:9.5
      environment:
        - POSTGRES_PASSWORD
        - POSTGRES_USER
        - POSTGRES_DB
      ports:
        - 5432:5432
